#!/bin/bash

commit=`git log --oneline -n 1`
regex="^[a-z0-9]+ publish: version [0-9]+\.[0-9]+\.[0-9]+$"

echo "Latest commit is: $commit"

if ! [[ $commit =~ $regex ]]
then
  echo "Not a publish commit, skipping publish."
  exit 0
fi

echo "Publishing new version."

npm i && \
rm -rf build && \
mkdir build && \
npm run compile && \
zip -r build/pkg.zip extension && \
curl \
-H "Authorization: Bearer $ACCESS_TOKEN" \
-H "x-goog-api-version: 2" \
-X PUT \
-T "build/pkg.zip" \
-v \
https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID && \
curl \
-H "Authorization: Bearer $ACCESS_TOKEN"  \
-H "x-goog-api-version: 2" \
-H "Content-Length: 0" \
-X POST \
-v \
https://www.googleapis.com/chromewebstore/v1.1/items/$APP_ID/publish
