#!/bin/bash

rm -rf build && mkdir build
rm -rf build/extension.zip && zip -r build/extension.zip extension

curl \
-H "Authorization: Bearer $ACCESS_TOKEN" \
-H "x-goog-api-version: 2" \
-X PUT \
-T "build/extension.zip" \
-v \
"https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID"
