#!/bin/bash

commit=`git log --oneline -n 1`
regex="^[a-z0-9]+ publish: version [0-9]+\.[0-9]+\.[0-9]+$"

echo "Latest commit is: $commit"

if ! [[ $commit =~ $regex ]]
then
  echo "Not a publish commit, exiting."
  exit 0
fi

echo "Publishing new version."

GOOGLE_ACCESS_TOKEN=`curl \
-X POST \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "client_id=$GOOGLE_CLIENT_ID&client_secret=$GOOGLE_CLIENT_SECRET&refresh_token=$GOOGLE_REFRESH_TOKEN&grant_type=refresh_token" \
https://www.googleapis.com/oauth2/v4/token | jq ".access_token"`

npm i && \
rm -rf build && \
mkdir build && \
npm run compile && \
zip -r build/pkg.zip extension && \
curl \
-H "Authorization: Bearer $GOOGLE_ACCESS_TOKEN" \
-H "x-goog-api-version: 2" \
-X PUT \
-T "build/pkg.zip" \
-v \
https://www.googleapis.com/upload/chromewebstore/v1.1/items/$GOOGLE_APP_ID && \
curl \
-H "Authorization: Bearer $GOOGLE_ACCESS_TOKEN"  \
-H "x-goog-api-version: 2" \
-H "Content-Length: 0" \
-X POST \
-v \
https://www.googleapis.com/chromewebstore/v1.1/items/$GOOGLE_APP_ID/publish
